version: '3.8'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000
      - APP_HOST=backend
      - APP_PORT=3000
      - VPC_CIDR=localhost

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - SANITY_TOKEN=${SANITY_TOKEN}
    ports:
      - "3000:3000"
